apiVersion: apps/v1
kind: Deployment
metadata:
  name: devday-app
  labels:
    app: devday-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devday-app
  template:
    metadata:
      labels:
        app: devday-app
    spec:
      containers:
        - name: devday-app
          image: CONTAINER_IMAGE